### PR TITLE
Browser refresh resets selections bug

### PR DESCRIPTION
**Pull request by korolainenriikka**
- questions set to state in getStaticProps
- removed -1 initialization in state (unnecessary)
- selections stored in sessionStorage

### CODE REVIEW

**Review by lehtoneo — CHANGES_REQUESTED** [review]
Does this break now if initial answers aren't initialized with -1?

const checkAllQuestionsAnswered = () => {
    let allAnswered = true
    store.selections.forEach(selection => {
      
      if (selection === -1) {
        allAnswered = false
      }
    })
    return allAnswered
  }

**Comment by Nurou** [comment]
Why not use persist middleware to persist our store?

It's documented here:
 https://github.com/pmndrs/zustand#persist-middleware

**Review by Nurou — CHANGES_REQUESTED** [review]
Why not use persist middleware to persist our store?

It's documented here:
 https://github.com/pmndrs/zustand#persist-middleware

Should also work with SSR, some discussion here:
https://github.com/pmndrs/zustand/pull/275

**Comment by korolainenriikka** [comment]
persis state -pull request solves this better.

**Pull request closed without merging**
